// SPDX-FileCopyrightText: Copyright 2026 Eden DSMod fork
// SPDX-License-Identifier: GPL-3.0-or-later

// Battle page art for Dragon Quest III HD-2D Remake 1.1.0.0, composed at runtime from the player's
// own Nicola-Switch.pak (pinned members in dq3_battle_pins.inc, generated by research
// tools/dq3-battle-pins.py). Owner-approved revision 2 "current-compact" battle layout.
//
// Monster sprites: the battle unit's FName +0x110 (GOP_Unit_Master row) -> GopIdUnitLooks ->
// DataAssetGOPUnitLooks blueprint -> SpriteManagerComponent.DefaultAnimationDatas[BattleIdle] ->
// NicolaAnimationData.Data[CHARACTER].Flipbook -> key frame 0, BOTTOM -> PaperSprite frame
// (BakedSourceTexture / UV / Dimension). Drawn like the design's mon_sprite: integer nearest
// scale = max(1, min(max_h / h, max_w / w)); a frame larger than the box is reduced with the
// LANCZOS resize (never upscaled with filtering).
//
// Keys (without "module:dq3:"), revision 2 "current-compact" (research design/redesign-2026-10/current-compact):
//   light/<w>x<h>                         T_UI_TravelInfo_Window_BG_00, margin trimmed, nine-sliced 78 -> 26 px
//   ecell/<s>/<w>x<h>/<sp_h>/<mode>/<f>   cell (box w x h at (CellGlow, CellGlow) of a canvas CellGlow px
//                                         larger on every side): thin outline, or the glow + gold box when f
//                                         has 's'; sprite s (-1 none), greyed (luma, alpha x 0.35) when f has
//                                         'g'; mode 1 = above a name (bottom at 6 + sp_h, scale <= 2), 0 =
//                                         centred (scale <= 3)
//   rowglow/<w>x<h>                       the cell glow with an 8 px spread (Bag list selection)
//   mon/<s>/<w>x<h>[/<k>]                 monster sprite s centred on a w x h canvas (integer scale <= k)
//   tabs/<w>x<h>/<sel>/<chev_x>           two command tabs (window 0.88, gold ring on <sel>, separator,
//                                         34 px chevron at chev_x)
//   outline/<w>x<h>                       gold selection outline (inset 2, radius 10, 3 px)
//   chev/<px>, down/<px>                  T_UI_Common_Select_00, and turned 90 degrees clockwise
//   shadowq/<px>                          T_UI_FieldRecord_MonsterShadow_00 cell 0 (the "?" slime)
//   affgrid/<w>x<h>/<cols>[/<rows>]       thin brown (150, 118, 76) grid: frame + column (and row) lines
//   spell/<cell>/<px>[/g]                 T_UI_Common_SpellIcon_00 cell (4 x 2), GOP_Magic.UIIconNo; g greyed
//   pcsprite/<n>/<h>/<b|c>                class sprite n (dq3_sprites.h) at 2x nearest, cropped to h
//                                         rows, centred on a PcSpriteW x h canvas, bottom-aligned
//                                         (b, the battle card above the name) or centred (c, under MP)
#pragma once

#include <optional>
#include <span>
#include <string_view>

#include "dq3_pak.h"
#include "dq3_sprites.h"

namespace dq3 {

inline constexpr u32 PcSpriteW = 160;
inline constexpr int CellGlow = 12; ///< selection glow spread around a grid cell (gen_manifest GLOW)

std::span<const SpritePin> MonsterSpritePins();
/// Sprite index of a GOP_Unit_Master row (the unit's +0x110 FName text).
std::optional<u32> FindMonsterSprite(std::string_view unit_master);

enum class BattleTable : u32 {
    MonsterAsset, MonsterExp, ResistAsset, ResistExp, MagicAsset, MagicExp, ItemAsset, ItemExp,
    ActionAsset, ActionExp, ActionListAsset, ActionListExp
};
const PakMember& BattleTableMember(BattleTable id);

/// Composes a battle key (nullopt when the key is not a battle key or the decode failed).
std::optional<Image> ComposeBattleArt(const RangeReader& read, std::string_view key,
                                      std::string* why = nullptr);
/// True when `key` belongs to ComposeBattleArt.
bool IsBattleArtKey(std::string_view key);

/// The design's integer sprite scale (render-design-revision2.py fit_scale), or 0 when the frame
/// must be reduced to fit.
int MonsterScale(u32 w, u32 h, u32 max_w, u32 max_h);

} // namespace dq3
