// SPDX-FileCopyrightText: Copyright 2026 Eden DSMod fork
// SPDX-License-Identifier: GPL-3.0-or-later

// Affinity element icons for Dragon Quest III HD-2D Remake 1.1.0.0 (enemy detail grid, 0.10.1-dev).
//
// The game has no per-element UI icon (all six attack-spell families use cell 0 of
// T_UI_Common_SpellIcon_00; GOP_Magic UIIconNo is 0 for each; no element art in any UI texture, rich-text
// table, monster record or Battle Road widget of the 1.1.0.0 archive). Each icon is therefore built at
// runtime from the game's own battle-effect textures (pinned members in dq3_element_pins.inc, generated by
// research tools/dq3-element-pins.py), tinted like the spells' own material instances tint them
// (M_EF_Common_01 Color-0.0 -> Color-1.0, values read from the cooked MIs), on the dark rounded tile of
// T_UI_Common_Status_StatusIcon_00. The specification is research runs/element-icons-0.10.1
// tools/element_ref.py; this file follows it operation by operation (results are close, not identical:
// the LANCZOS resize is the Pillow-like dq3::Resize).
//
//   Frizz  T_EF_Glow_05 profile + T_EF_Noise_04 licks on a flame silhouette (the archive has no shaped fire
//          texture: Mera / Merami / Merazoma are meshes with noise); MI_EF_Btl_Mera_Fire_DepthOFF_01 body,
//          MI_EF_Btl_Mera_Impact_DepthOFF_01 core
//   Sizz   T_EF_Line_03 flame-tongue row on an arc; MI_EF_Btl_PL_Mgc_Gira_02
//   Bang   T_EF_Shock_01_A rays + T_EF_Particle_01 core; MI_EF_Btl_MS_Iora_Flare_DepthOFF_01
//   Crack  T_EF_IceBlock_01 (BC7 colour, two chips, as MI_EF_Btl_MS_Hyado_IceChip_01 draws it)
//   Woosh  T_EF_AuraTrail_01_A, three bent streaks; MI_EF_Btl_Bagima_02
//   Zap    T_EF_Thunder_02 bolt; MI_EF_Btl_Raidein_Thunder_01
//
// Key (without "module:dq3:"): elem/<k>/<px>  element k (0..5, ResistElements order) on a px x px tile
// (16..128). The 256 px master glyph of each element is composed once and kept; each tile size is kept
// after its first use.
#pragma once

#include <array>
#include <memory>
#include <optional>
#include <span>
#include <string>
#include <string_view>

#include "dq3_pak.h"

namespace dq3 {

/// A pinned cooked effect texture: the .uexp and, when the first mip is bulk data, the .ubulk member.
struct EffectTexturePin {
    std::string_view name;
    PakMember uexp;
    PakMember bulk; ///< path empty when the first mip is inline
    u32 w, h;
    u32 format;     ///< 0 PF_BC7, 3 PF_BC4
    u32 pf_at;      ///< offset of the "PF_..." string in the .uexp (dimensions at pf_at - 16)
    u32 mips;
    u32 flags;      ///< first mip record flags (72 inline, 0x10501 bulk)
    u32 data_bytes;
    u32 data_at;    ///< inline data offset in the .uexp (0 for bulk)
    u64 bulk_offset;
    bool has_bulk;
};

enum class ElemTex : u32 { Glow05, Noise04, Line03, Shock01A, Particle01, IceBlock01, AuraTrail01A, Thunder02, Count };
std::span<const EffectTexturePin> ElementTexturePins();

inline constexpr int ElementCount = 6;
inline constexpr u32 ElementMaster = 256;

/// Decodes a pinned effect texture member pair (layout checked against the pin) to straight RGBA8; a BC4
/// texture decodes into R (G = B = R, A = 255).
std::optional<Image> DecodeEffectTexture(std::span<const u8> uexp, std::span<const u8> bulk,
                                         const EffectTexturePin& pin, std::string* why = nullptr);

/// The 256 x 256 master glyph of element k (cached after the first build).
std::shared_ptr<const Image> ElementGlyph(const RangeReader& read, int k, std::string* why = nullptr);

bool IsElementArtKey(std::string_view key);
/// Composes elem/<k>/<px> (nullopt for another key or a failed decode).
std::optional<Image> ComposeElementArt(const RangeReader& read, std::string_view key, std::string* why = nullptr);

#ifdef DQ3_TEST_API // test-only API: defined for the dsmod-dq3 test target, not compiled into the module
/// The tonemapped ramp colour (sRGB 8-bit) of glyph ramp r at t (for tests / documentation).
std::array<u8, 3> ElementRampColour(int ramp, double t);
#endif

} // namespace dq3
