// SPDX-FileCopyrightText: Copyright 2026 Eden DSMod fork
// SPDX-License-Identifier: GPL-3.0-or-later

// Field Map page of the Dragon Quest III HD-2D Remake companion (Switch 1.1.0.0, build
// 4F41309B39EEBE5E): game data, the live location reader, the page values and the page art.
// Research contracts (research/dragon-quest-iii-hd-2d-remake): LOCATION.md, DUNGEON-FLOORS.md,
// runs/slice3-map/RESULT.md. Read-only: no guest writes, no guest calls.
//
// Game data (parsed at runtime from the player's own Nicola-Switch.pak, pins in dq3_map_pins.inc
// generated by research tools/dq3-map-pins.py):
//   GOP_MapList       row = current MapID (MAPLIST_*): NameTextID (the native Map title), MapImage
//                     (soft path -> a pinned texture), MapOriginalPos O / MapSize S (marker formula),
//                     PrefixId + MapFloorGroup + MapFloorSortNum (the floor selector), the day / night
//                     GOP_Map_SpotIcon rows and MapSpotIconIndex (interiors), IsUnderground.
//   GOP_Map_SpotIcon  12 entries {EMapSpotType, DispPosition (image px), display / hide progress}.
//   GOP_Hour          in-game hour -> EMapTimeFrame.
//   GOP_Text_Noun_ENGLISH  ListNoun of every TEXT_NOUN_ENGLISH_Map_* row (place / floor names).
//   en/GOP_Text_Map   Txt_Map_Menu_World_Map / _Alefgard_Map: the world map titles.
//
// Rules taken from the game's code (main-relative, 1.1.0):
//   0xbfa52c  town / dungeon marker: u = clamp((Y - O.y) * W / S.y, 0, W),
//             v = clamp(H - (X - O.x) * H / S.x, 0, H) on the W x H map image (X, Y sublevel-local).
//   0xbfa204  MapSpotIconIndex k != 0 (interiors that reuse the town image): the marker sits at spot
//             entry k (1-based) of the day / night spot row, PLAYER_SPOT_POS_Y_OFFSET lower unless
//             that entry is a HOUSE.
//   0xce4170  spot entries: row +0x124 (day) when GetMapTimeFrame != NIGHT (0xbe5db8), else +0x12c;
//             an entry shows when (display flag 0 or set) and not (hide flag set); the flags are
//             progress bits (0x877570: index <= 0xac, qword P + 0x1f0 + 8 * (i >> 6)).
//   0xce4130  GetFacilityIconIndex: type 1..14 -> float table main+0x490a108 (+15 for the map-sized
//             set the full map uses), HOUSE / NONE -> no icon. Cells of T_UI_Map_Facility_Icon_01
//             (5 x 6 cells of 88 px).
//   0xa2146c / 0xa213c8  MapTimeManager (world subsystem) float +0x30 = seconds:
//             hour = ((int)t % 86400) / 3600 -> GOP_Hour row HOUR_Hour%02d -> MapTimeFrame.
//   0xbfa518  the player icon angle = the root component world Yaw (clockwise, 0 = north).
//   0xbd96e8  the Map screen's time symbol: cell 1 (moon) when MapTimeFrame == NIGHT, else cell 0.
//   0xbd795c / 0xbd7bd0  world map extent: NicolaDataAssetCommon [G+0x4b8]: origin +0x168, tile
//             count (int) +0x170, tile size +0x178 (FIELD1); +0x180 / +0x188 / +0x190 underground.
//             The world image spans the extent: u = (Y - O.y) / (n.y * t.y) * W,
//             v = (1 - (X - O.x) / (n.x * t.x)) * H.
//   Visited maps P+0x250 (TArray<FName>) = the native floor selector's list (LOCATION.md §4).
//   Chests opened: the current map's *_SearchObj sublevel actors' SearchObjEventTrigger
//             (+0xF8 SearchObjEventGopId, +0x102 flag, +0x105 ESearchObjectType); IsTreasure
//             (0x845a00: type - 11 < 4, TREASURE_*); opened = bit `flag` of the P+0x128 bitset
//             (SetFlag 0x87aa3c with the trigger's +0x102 at 0x845958).
#pragma once

#include <array>
#include <cstdint>
#include <functional>
#include <map>
#include <memory>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <vector>

#include "dq3_font.h"
#include "dq3_pak.h"
#include "dq3_reader.h"

namespace dq3 {

// ---------------------------------------------------------------------------------- game data
struct SpotEntry {
    u8 type{};          ///< EMapSpotType (0 NONE .. 15 HOUSE)
    float x{}, y{};     ///< DispPosition (map image px)
    u32 disp{}, hide{}; ///< progress flag values (0 = none)
};
struct MapRow {
    std::string name_text, telop_text, prefix;
    int image{-1};               ///< index into MapImagePins(), -1 = no image
    float ox{}, oy{}, sx{}, sy{}; ///< MapOriginalPos / MapSize
    int floor_group{}, floor_sort{};
    std::string spot_day, spot_night;
    int spot_index{};
    bool underground{};
    std::string field_symbol;
    std::string memory; ///< MemoryID (GOP_Memory row: the place the map belongs to), "None" / "" = none
};
struct DestinationRow {
    std::string floor, tag;
    int type{12}; ///< EMapLocationIconType, NUM=12
    std::string area; ///< AreaNameId (the place's name text; its FloorID is the place's town map)
};
struct WorldIcon {
    int type{};
    float x{}, y{}; ///< world coordinates of the native MapIconPlayerStartTag actor
    bool underground{};
    bool operator==(const WorldIcon&) const = default;
};
struct MapData {
    struct Guide { std::string message; std::vector<std::string> world, town; };
    std::vector<Guide> guides;
    std::map<std::string, DestinationRow, std::less<>> destinations;
    std::map<std::string, MapRow, std::less<>> rows;
    std::map<std::string, std::array<SpotEntry, 12>, std::less<>> spots;
    std::array<int, 24> hour_frame{}; ///< EMapTimeFrame by hour (1 DAYTIME, 2 EVENING, 3 NIGHT)
    std::map<std::string, std::u32string, std::less<>> nouns; ///< "Txt_Map_..." -> ListNoun
    std::map<std::string, std::u32string, std::less<>> menu;  ///< GOP_Text_Map Txt_Map_Menu_* text
    std::map<std::string, std::string, std::less<>> memory_area; ///< GOP_Memory MemoryID -> AreaNameId
    const std::u32string* Noun(std::string_view text_id) const {
        const auto it = nouns.find(text_id);
        return it == nouns.end() ? nullptr : &it->second;
    }
    const MapRow* Row(std::string_view id) const {
        const auto it = rows.find(id);
        return it == rows.end() ? nullptr : &it->second;
    }
};

/// ASTC 8x8 decode (the host's decode_astc): width, height, blocks in, RGBA8 out.
using AstcFn = std::function<bool(u32, u32, const u8*, std::size_t, u8*, std::size_t)>;

struct MapTexturePin {
    std::string_view name; ///< texture object name
    PakMember member;
    u32 w, h;
    u32 format; ///< 0 BC7, 1 ASTC 8x8 (host decode_astc), 2 B8G8R8A8
    u32 pf_at, data_at, data_bytes;
    u32 mip_count{1}; ///< first inline mip is decoded; underground detail textures contain 11
};
std::span<const MapTexturePin> MapImagePins();
int FindMapImage(std::string_view texture_name);
enum class MapUi : u32 {
    Frame, NowLocation, WorldNowLocation, Facility, TimeSymbol, Coins, Treasure, TitleBg,
    MapMenuIcon, HealEffect, CharaJob, Saving, Select, WindowBase, TravelBg, WorldFacility, Count
};
const MapTexturePin& MapUiPin(MapUi id);

/// Parses the pinned tables (once; thread-safe). nullptr until built.
std::shared_ptr<const MapData> LoadMapData(const RangeReader& read, std::string* why = nullptr);
std::shared_ptr<const MapData> CachedMapData();
/// Builds from caller-supplied members (tests): uasset/uexp of GOP_MapList, GOP_Map_SpotIcon,
/// GOP_Hour, GOP_Text_Noun_ENGLISH, en/GOP_Text_Map.
std::optional<MapData> BuildMapData(std::span<const std::span<const u8>, 10> members,
                                    std::string* why = nullptr);


/// Decodes a pinned texture member (checks the layout, then BC7 / BGRA / ASTC through `astc`).
std::optional<Image> DecodeMapTexture(std::span<const u8> uexp, const MapTexturePin& pin,
                                      const AstcFn& astc,
                                      std::string* why = nullptr);

// ---------------------------------------------------------------------------------- live state
struct MapRoots {
    bool ok{};
    std::array<int, 14> facility_cell{}; ///< the float table main+0x490a108 (GetFacilityIconIndex)
};
/// Checks the code pins of the Map page rules and reads the facility table. Empty = ok.
std::string ResolveMap(const GuestRead& read, std::uint64_t main_base, std::uint64_t main_size,
                       MapRoots& roots);

struct WorldExtent {
    bool ok{};
    float ox{}, oy{}, w{}, h{}; ///< origin and size (world units)
};
struct LocationSnapshot {
    std::string map_id;       ///< MAPLIST_* (LLM+0x1B4)
    std::string pawn_class;   ///< BP_TownDungeonPlayer_C, BP_FieldTopPawn_C, BP_PlayerShip_C, ...
    bool have_pos{};
    float x{}, y{};           ///< sublevel-local position (town / dungeon) or world (field)
    float facing_deg{};       ///< clockwise from map north
    bool facing_ok{};
    std::uint32_t gold{};     ///< P+0x28
    std::uint32_t medals{};   ///< P+0x34, native Mini Medals count
    int hour{-1};             ///< in-game hour (MapTimeManager)
    std::array<std::uint64_t, 3> progress{}; ///< progress bits 0..191 (P+0x1F0)
    bool operator==(const LocationSnapshot&) const = default;
};
struct LocationCache {
    std::uint64_t world{}, llm{}, time_mgr{};
    WorldExtent field[2];
    std::map<std::string, std::pair<float, float>, std::less<>> world_anchors;
    std::map<std::uint64_t, std::string> class_names; ///< UClass* -> name (small)
};
/// One read of the current location (the scene must be in an adventure and not loading).
bool ReadLocation(const GuestRead& read, const Roots& roots, const SceneState& scene,
                  std::uint64_t pawn, LocationCache& cache, LocationSnapshot& out,
                  std::string* why = nullptr);
/// The visited-maps array P+0x250 as MAPLIST_* names (bounded to 4096 entries).
std::optional<std::vector<std::string>> ReadVisited(const GuestRead& read, const Roots& roots);
/// ReadChests' state between calls: UClass* -> name, and per loaded _SearchObj level the actor array last
/// scanned with the save flags of its treasure triggers. A level whose actor array (address, count and
/// every pointer) is unchanged reuses its flags instead of reading each actor again; only the progress
/// bits are read. Clear it on a new resolve (fresh pool) or map / world change.
struct ChestScan {
    struct Level {
        std::uint64_t lsd{}, level{}, array{};
        std::vector<std::uint64_t> actors;
        std::vector<std::uint16_t> flags; ///< TrigFlag of each treasure trigger, in actor order
    };
    std::vector<Level> levels;
    std::map<std::uint64_t, std::string> classes;
    void Clear() {
        levels.clear();
        classes.clear();
    }
};
/// Search objects of the current map: {treasures, treasures opened} (nullopt when unreadable).
std::optional<std::pair<int, int>> ReadChests(const GuestRead& read, const Roots& roots,
                                              std::uint64_t llm, std::string_view map_id, ChestScan& scan);

/// Visited world destinations only; static anchors from ActorListMan PlayerStarts.
std::optional<std::vector<WorldIcon>> ReadWorldIcons(const GuestRead& read, const Roots& roots,
    const MapData& data, const LocationSnapshot& loc, LocationCache& cache);
bool WorldVariantVisible(std::string_view id, const LocationSnapshot& loc);

enum class FieldMenuMode { Field, Top, Misc, LineUp, Other };
struct FieldMenuState {
    FieldMenuMode mode{FieldMenuMode::Other};
    int cursor{-1}, command{-1};
    int selected{-1}, count{}; ///< native Line-Up selection and party size
    bool operator==(const FieldMenuState&) const = default;
};
/// One UI widget-manager controller: its class name and the list state +0x88 (AddController 0xaa54d8 stores 1 =
/// active, taking input; 0xae9010 2 = a child list is open; 0xaa5520 3 = closing; 0xaa4f80 0; contracts/
/// BATTLE-MENU-FOLLOW.md). The state word is meaningful for the *List* controllers only.
struct UiController {
    std::string name;
    std::int32_t state{};
    bool operator==(const UiController&) const = default;
};
/// The UI widget manager's controllers (G+0x418 BP_NicolaUIManager_C -> +0x7C0 BP_UIWidgetManager_C -> TArray
/// +0x298 / +0x2A0, the chain ReadFieldMenu reads), in list order. nullopt when unreadable. On the title world:
/// UITitleDemoMenu* (press a button) or UITitle2Menu* (Venture Forth / the save list / the Yes-No); after a save
/// is confirmed no list is active any more while the title shows the game's loading book, until the world goes
/// (research runs/system-screens logs/title-flow-controllers.txt).
std::optional<std::vector<UiController>> ReadUiControllers(const GuestRead& read, const Roots& roots,
                                                           std::map<std::uint64_t, std::string>* class_names = nullptr);
/// The native field menu state from the UI widget manager's controller list. `class_names`
/// (optional) keeps UClass* -> name between calls; the caller clears it when the world changes.
std::optional<FieldMenuState> ReadFieldMenu(const GuestRead& read, const Roots& roots,
                                            std::map<std::uint64_t, std::string>* class_names = nullptr);

// ---------------------------------------------------------------------------------- page values

struct MapViewInput {
    const FontAtlas* font{}; ///< fits the banner title and the floor names (nullptr: the largest sizes)
    const std::u32string* objective{}; ///< the native current objective (Journal's MapGuide reader), if any
    std::string hero_sprite{"-"};      ///< the no-map card's sprite (the hero's looks index, "-" = none)
    const MapData* data{};
    const MapRoots* roots{};
    const LocationSnapshot* loc{};
    const std::vector<std::string>* visited{};
    const WorldExtent* world{}; ///< [IsUnderground] world extent of the current field map
    std::optional<std::pair<int, int>> chests;
    const std::vector<WorldIcon>* world_icons{};
    int browse{}; ///< floor offset from the current one (stepper), clamped by the builder
    int zoom{}; ///< 0 local/minimap, 1 island/region, 2 overall world
    std::optional<std::pair<float, float>> area_anchor; ///< native field symbol location, not a live pawn
    bool full{};  ///< full-size map
    bool visible{}; ///< the Map tab is open (every gate is 0 otherwise)
};
struct MapView {
    std::map<std::string, std::int64_t> ints;
    std::map<std::string, std::string> texts;
    int browse{}; ///< the clamped browse offset
    bool operator==(const MapView&) const = default;
};
MapView BuildMapView(const MapViewInput& in);

/// The facility atlas cell of a spot type (map-sized set when `large`), -1 = not drawn.
int FacilityCell(const MapRoots& roots, u8 type, bool large);
/// Companion legend label of an EMapSpotType (the game shows no names).
std::string_view SpotLabel(u8 type);

// Layout (revision 2 "current-compact" map page; 1240 x 1080 canvas; gen_manifest.py checks these)
inline constexpr int MapX0 = 36, MapY0 = 32, MapX1 = 1204;
inline constexpr int MapPageY = 228, MapPageH = 724; // FPAGE_Y, FPAGE_H
inline constexpr int FullMapY = 32, FullMapH = 1016;
inline constexpr int MapLeftW = 384, MapGap = 8, MapFin = 30, MapButton = 88;
inline constexpr int MapTitleRoom = 280;            // banner text room between the TitleBG end ornaments
inline constexpr int MapCardY = 296;                // the light info card under the banner
inline constexpr int MapRightX = MapX0 + MapLeftW + MapGap; // 428
inline constexpr int MapRightW = MapX1 - MapRightX;         // 776
inline constexpr int MarkerPx = 52, WorldMarkerPx = 64;

// ---------------------------------------------------------------------------------- no-map states
// Owner-approved mix (research design/redesign-2026-10/no-map): the Map tab never shows an empty frame.
//   Card  (C)  the title-flame card ("Your journey begins", the native objective, the hero): the location is
//              not read yet / the row is unknown, an image-less row without a place (the dream maps S01..S09),
//              and the pinned CardRows (image-less rows with a MemoryID but no GOP_TownDungeonSublevel row:
//              MAPLIST_C01R1001).
//   Place (B)  an image-less row whose MemoryID (GOP_Memory -> AreaNameId) has the game's TitleDemo still
//              (pinned PlaceArt table): the still for the time frame, the place and region names, a Town Map
//              button (the place's town map: GOP_Rura_Riremito AreaNameId -> FloorID). MAPLIST_C01R1101 (the
//              Aliahan event map: the hero's house and the castle's 2F in one map) uses it: the game data does not
//              tell which of the two the hero is in, so the parent-map marker (A) is not drawn there.
// Rows with an image keep the map. Only field rows fall back to the "World Map" title.
enum class NoMapState : u8 { Map, Card, Place };
struct NoMapView {
    NoMapState state{NoMapState::Map};
    int variant{};        ///< Card copy: 0 the journey begins (Aliahan's town not visited yet), 1 a place without
                          ///< a map, 2 the location is not read
    int art{-1};          ///< Place: PlaceArt index
    std::string area;     ///< Place: AreaNameId
    std::string region;   ///< Place: the region line's text id
    std::string town_row; ///< Place: the town map row, "" = none
};
/// `row` = the current MapList row (nullptr: not read / unknown); `visited` = P+0x250 (nullptr: unread).
NoMapView SelectNoMap(const MapData* d, const MapRow* row, std::string_view map_id,
                      const std::vector<std::string>* visited);
#ifdef DQ3_TEST_API // test-only API: defined for the dsmod-dq3 test target, not compiled into the module
/// The pinned PlaceArt places (MemoryIDs), in table order.
std::vector<std::string_view> PlaceArtPlaces();
#endif
/// The card's emblem (T_UI_TitleDemo_TitleLogo_Emblem_01_JEK), decoded once.
std::shared_ptr<const Image> NoMapEmblemTexture(const RangeReader& read, std::string* why = nullptr);
// Card layout inside the 1168 x 724 page box (render no-map option_c), shared with gen_manifest.py and the
// card composer (dq3_system.cpp sys/card/): emblem box, headline / line baselines, objective window.
inline constexpr int CardW = 1168, CardH = 724;
inline constexpr int CardEmblemY = 56, CardEmblemW = 300, CardEmblemH = 170;
inline constexpr int CardHeadY = 296;                     // CardEmblemY + CardEmblemH + 70
inline constexpr int CardObjY = 388, CardObjH = 72;       // the objective window (CardHeadY + 92)
inline constexpr int CardObjPad = 120, CardObjText = 72;  // window = text + 120; text 72 px in

// ---------------------------------------------------------------------------------- page art
/// True when `key` belongs to ComposeMapArt.
bool IsMapArtKey(std::string_view key);
/// Composes a Map page key (see dq3_map.cpp). `astc` decodes ASTC 8x8 blocks.
std::optional<Image> ComposeMapArt(const RangeReader& read, std::string_view key,
                                   const AstcFn& astc,
                                   std::string* why = nullptr);

} // namespace dq3
