// SPDX-FileCopyrightText: Copyright 2026 Eden DSMod fork
// SPDX-License-Identifier: GPL-3.0-or-later

// Party and Journal tabs of the Dragon Quest III HD-2D Remake companion (Switch 1.1.0.0, build
// 4F41309B39EEBE5E): game data, the live readers and the rules the native menus use. Read-only: no
// guest writes, no guest calls. Research: runs/party-journal-tabs (research/dragon-quest-iii-hd-2d-remake).
//
// Game data (parsed at runtime from the player's own Nicola-Switch.pak; pins in dq3_info_pins.inc,
// generated by research tools/dq3-info-pins.py; GOP_Item / GOP_Magic / GOP_Monster / the noun table
// reuse the battle pins):
//   GOP_Personality      PERSONALITY_* -> DisplayNameId; the native Status shows the noun table's
//                        ListNoun of that id (e.g. PERSONALITY_AMAZON -> "Bodybuilder")
//   GOP_LevelUpExp       LEVELUPEXP_<level> -> the total EXP per vocation column
//   GOP_Item             ParamType +0xC9, ParamUpType +0xCA, ParamValue +0xCC, ParamFighterDown +0xD4
//                        (row offsets the stat getters read), UIIconNo, NameTextId, FlavorTextId
//   GOP_Magic            FlavorTextId (the Spells description)
//   GOP_Information      Traveller's Tips: SortOrder, InformationTitleId, DispFlagName (EGOPEnumProgressType)
//   GOP_Medal            RequireMedal, Product_0 (table order)
//   GOP_Monster_Library  the native Defeated Monster List rows (Numerical Order = TypeSortNo), habitat ids,
//                        IsMoreHabitat ("and Elsewhere"), GopIdTrivia (Description)
//   GOP_Monster          EXP, Gold, Drop_Item of a library row's GopIdMonster
//   GOP_Unit_Master / GOP_Unit_Common  GopIdUnitCommon -> CharacterNameGopIdText (the monster's name)
//   GOP_MapGuide         TargetMain / TargetSub00..19 (MAPGUIDEDATA ids)
//   GOP_MapGuideData     DispTriggerEventID / CompleteTriggerEventID (progress conditions), MessageTextID
//   en GOP_Text_FieldMenu the native menu labels: Equip_BLANK_01..06 (the Equipment screen's slot names:
//                        Weapons .. Sub-Accessory), STATUS_PARAMNAME_* (stat names), Item_ITEMBAG /
//                        EQUIPBAG / IMPOTANT (bag names), Item_COUNTA_01 ("Number Held"), Top_EQUIP
//
// Rules taken from the game's code (main-relative, 1.1.0; every route below is pinned):
//   0x8d0294  personality = FName C+0xAC (written at creation 0x8a6220)
//   0x8d02a0  Exp. to Next Level = (level F+0x1C > 98) ? 0 : LevelExp(level + 1, vocation C+0xAA) - F+0x20;
//             0x8a44ec reads row "LEVELUPEXP_%d" and the vocation column (jump table: 1 Hero +0x10 ..
//             10 Monster Wrangler +0x34); vocation outside 1..10 or a missing row -> INT_MAX
//   stat getters (full path, clamp 0..999): s = F, or [F+0x1A8] while its controller F+0x1B0 holds a
//             shared reference; floor((float)double) of the base, the int bonus, and over the owner's
//             equipped items ([[F+8]+0x78] map) the item-row helpers:
//      0x89e2e0 Strength   base +0x38 bonus +0x70 (helper 0x87ef78 returns 0: no STR param type)
//      0x89e890 Resilience base +0x40 bonus +0x74 (helper 0x87ef80 returns 0)
//      0x89ee40 Agility    base +0x48 bonus +0x78 ADD 5 (0x87ef90) RATIO 5 (0x87f3f0)
//      0x89f620 Stamina    base +0x50 bonus +0x7C ADD 3 / RATIO 3
//      0x89fe00 Wisdom     base +0x58 bonus +0x80 ADD 4 / RATIO 4
//      0x8a05e0 Luck       base +0x60 bonus +0x84 ADD 6 / RATIO 6; an item effect of type 0x5E
//                          (LUCK_ZORO) in the bag's effect list B+0x88 overrides the value (0x8a0f10):
//                          that case is not reproduced and Luck is published as unavailable
//      ADD helper  = (row ParamType == t && ParamUpType == ADD ? ParamValue : 0) + the first entry of
//                    the item instance's extra list def+0x10/+0x18 {u8 ?, u8 type, u8 up, pad, s32 v}
//                    with that type and ADD (0 when none)
//      RATIO helper = the same with RATIO, the row value minus 100; per stat
//                    value = floor(base) + sum ADD + (floor(base) + bonus) * sum RATIO / 100 + bonus
//      0x8a1240 Attack  = GetStr + per item 0x87f24c: Fighter (vocation 3) with ParamFighterDown != 0 ->
//                         ParamFighterDown, else OFFENSE ADD ParamValue
//      0x8a1600 Defence = GetRes + per item 0x87f2e4 (DEFENSE ADD ParamValue)
//   0x89d2f0 / 0x89d590 Max HP / MP (full path, w1 = 0 as the UI calls it): clamp(F+0x28 / +0x30 + equipped
//             GOP_Item rows ParamType 7 MAXHP / 8 MAXMP with ADD (helpers 0x87eec0 / 0x87ef1c, no instance
//             extras) + F+0x68 / +0x6C, 0, 999); read from F, never the F+0x1A8 record. The 1.1.0.0 archive
//             has no MAXHP / MAXMP row, so the sum is 0 there (HasMaxHpMpItems).
//   0x8aa528  bag full: limit = B+0x21 (bLimitStockNum, set for every character bag) ? 20 : INT_MAX, full
//             when the slot count B+0x30 (equipped items included) reaches it; the Party tab's "N / 20 held"
//   0xb9c480  Traveller's Tips list: GetAllRows(GOP_Information) where DispFlagName == 0 or the progress
//             bit is set, ordered by SortOrder (first minimum wins ties); 0xb9c730 the "!" (unread) icon
//             = byte [R+0x18][table index] == 0 (0x8737c4, bound R+0x20), R = [GD+0x48] (0x873530)
//   0xc09d40  next Mini Medal reward: among GOP_Medal rows not in P+0x40 (TArray<FName> received), the
//             smallest RequireMedal (first in table order on ties); claimable when P+0x34 >= it
//   0xc02da0  current MAPGUIDE: progress 56 (MAIN_LANCEL_StartTrial) set and 59 not set -> FName
//             MapGuideManager(G+0x480)+0x28, else FName R+0xC
//   0xc03c78  the objective banner: MessageTextID of MapGuideData[MapGuide.TargetMain] (no condition)
//   0xc02e90  its sub lines: TargetSub rows whose MessageTextID is set, Disp true and Complete false
//   0x84a330  a condition string: spaces removed; with '&' every token, with '|' the first decisive
//             token (an unknown / NONE token ends the scan false), else the single token; a token is
//             the EGOPEnumProgressType enumerator of that name (value 0 = false) and tests its bit
//   Defeated Monster List: record P+0x280 (TMap<FName UNIT_MASTER_*, int32 kills>, dq3_battle.h);
//             "Types of Monster Defeated" N / library rows; Experience / Gold Coins from GOP_Monster,
//             Item Dropped = the Drop_Item row's name or "N/A" (0xb83bb4), Primary Habitat from the
//             two habitat ids (+ "and Elsewhere"), Description = GopIdTrivia.
#pragma once

#include <array>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <vector>

#include "dq3_map.h"
#include "dq3_pak.h"
#include "dq3_reader.h"

namespace dq3 {

using u16 = std::uint16_t;

// ---------------------------------------------------------------------------------- game data
enum class InfoUi : u32 { ImageFrame, ItemType, ItemBg, BagIcon, NextGuide, Medal, Count };
const MapTexturePin& InfoUiPin(InfoUi id);

struct ItemRow {
    std::string name_text, flavor_text;
    int icon{};          ///< UIIconNo (T_UI_Common_ItemType_Icon_00 cell)
    u8 param_type{};     ///< EEquipParamType (0 NONE, 1 OFFENSE, 2 DEFENSE, 3 PHYSICAL, 4 INTELLIGENCE,
                         ///< 5 AGILITY, 6 LUC, 7 MAXHP, 8 MAXMP)
    u8 param_up{};       ///< EParamUpType (0 NONE, 1 ADD, 2 RATIO, 3 SPECIAL)
    s32 param_value{}, fighter_down{};
};
struct LibraryRow {
    std::string id, unit_master, monster, habitat[2], trivia, name_text;
    int sort{};
    bool more{};
};
struct MonsterRecordRow {
    s32 exp{}, gold{};
    std::string drop; ///< GOP_Item row or "None"
    bool boss{};      ///< Is_Boss (GOP_Monster +0x98)
};
struct InfoRow {
    std::string id, title;
    int sort{};
    u16 flag{}; ///< EGOPEnumProgressType value of DispFlagName
};
struct MedalRow {
    std::string id, product;
    s32 require{};
};
struct GuideRow {
    std::string main;
    std::vector<std::string> subs;
};
struct GuideDataRow {
    std::string disp, complete, message;
};

struct InfoData {
    std::map<std::string, ItemRow, std::less<>> items;
    std::map<std::string, std::string, std::less<>> magic_flavor; ///< GOP_Magic row -> FlavorTextId
    std::map<std::string, std::string, std::less<>> personality;  ///< PERSONALITY_* -> DisplayNameId
    std::map<int, std::array<s32, 10>> level_exp;                  ///< level -> per vocation 1..10
    std::vector<LibraryRow> library;                               ///< Numerical Order
    std::map<std::string, MonsterRecordRow, std::less<>> monsters; ///< GOP_Monster row
    std::vector<InfoRow> info;                                     ///< GOP_Information table order
    std::vector<MedalRow> medals;                                  ///< GOP_Medal table order
    std::map<std::string, GuideRow, std::less<>> guides;
    std::map<std::string, GuideDataRow, std::less<>> guide_data;
    std::map<std::string, std::u32string, std::less<>> texts; ///< flavour / tip-title texts
    std::map<std::string, std::u32string, std::less<>> nouns; ///< "Txt_..." -> ListNoun (personality,
                                                              ///< item, magic, monster, map)
    const std::u32string* Text(std::string_view id) const {
        const auto it = texts.find(id);
        return it == texts.end() ? nullptr : &it->second;
    }
    const std::u32string* Noun(std::string_view id) const {
        const auto it = nouns.find(id);
        return it == nouns.end() ? nullptr : &it->second;
    }
};

/// Parses the pinned tables (once; thread-safe). nullptr until built.
std::shared_ptr<const InfoData> LoadInfoData(const RangeReader& read, std::string* why = nullptr);
/// The level of a GOP_LevelUpExp row id "LEVELUPEXP_<n>" (a whole decimal int); false otherwise.
bool ParseLevelRowId(std::string_view id, int& level);
std::shared_ptr<const InfoData> CachedInfoData();
/// The progress enumerator value of "EGOPEnumProgressType::<token>" (nullopt = unknown name).
std::optional<u16> ProgressValue(std::string_view token);

// ---------------------------------------------------------------------------------- rules
struct Progress {
    std::array<std::uint64_t, 3> bits{}; ///< P+0x1F0 (0..191); the game tests indices <= 0xAC
    bool Test(u32 i) const {
        return i <= 0xAC && ((bits[i >> 6] >> (i & 63)) & 1) != 0;
    }
};
/// 0x84a330: a DispTriggerEventID / CompleteTriggerEventID string against the progress bits.
bool EvalCondition(std::string_view condition, const Progress& p);

/// 0x8a44ec: total EXP at `level` for vocation 1..10 (nullopt = INT_MAX in the game).
std::optional<s32> LevelExp(const InfoData& d, int level, int vocation);
/// 0x8d02a0: Exp. to Next Level (0 at level 99).
std::optional<s32> ExpToNext(const InfoData& d, int level, int vocation, s32 exp);

struct OwnedItem {
    std::string id;     ///< GOP_Item row
    s32 count{};
    u8 equip{};         ///< 0 = not equipped, 1 weapon .. 6 sub-accessory
    std::vector<std::array<u8, 8>> extras; ///< item-instance params def+0x10 (8-byte entries)
    bool operator==(const OwnedItem&) const = default;
};
struct StatInputs {
    std::array<double, 6> base{}; ///< Str, Res, Agi, Stamina, Wis, Luck (s = F or the F+0x1A8 record)
    std::array<s32, 6> bonus{};
    u8 vocation{};
    std::vector<OwnedItem> items; ///< the owner's bag (equipped ones count)
    bool luck_override{};         ///< a LUCK_ZORO effect in B+0x88
    /// GetMaxHP / GetMaxMP inputs, always from F itself (those getters never take the F+0x1A8 record):
    /// base F+0x28 / +0x30, bonus F+0x68 / +0x6C
    s32 hp_base{}, hp_bonus{}, mp_base{}, mp_bonus{};
    bool operator==(const StatInputs&) const = default;
};
struct Stats {
    s32 strength{}, resilience{}, agility{}, stamina{}, wisdom{}, luck{}, attack{}, defence{};
    s32 max_hp{}, max_mp{}; ///< GetMaxHP / GetMaxMP full path (equipment included)
    bool luck_ok{true};
};
Stats ComputeStats(const InfoData& d, const StatInputs& in);
/// The equipment term of GetMaxHP (0x89d2f0, type 7 MAXHP, helper 0x87eec0) / GetMaxMP (0x89d590, type 8
/// MAXMP, helper 0x87ef1c) full path, w1 = 0 as nearly every UI caller passes it (the status window, HP
/// state 0xce2544, the field menus): the sum over equipped items of the GOP_Item row's ParamValue when
/// ParamType == type and ParamUpType == ADD. Unlike the 0x87ef90 shape these helpers read no item-instance
/// extras and no RATIO. Displayed max = clamp(base + this + bonus, 0, 999) = DisplayedMax(base + this, bonus).
s32 EquipMaxParam(const InfoData& d, const std::vector<OwnedItem>& items, u8 type);
/// True when some GOP_Item row has ParamType MAXHP / MAXMP with ADD, i.e. when EquipMaxParam can be
/// non-zero at all (none in the 1.1.0.0 archive: its 301 rows have no such row).
bool HasMaxHpMpItems(const InfoData& d);
/// One item's ADD (up 1) or RATIO (up 2, minus 100) value for param type `type`: the GOP_Item row's
/// value when its ParamType / ParamUpType match, plus the first matching item-instance extra (the
/// 0x87ef90 helper shape the stat getters sum).
s32 ItemParam(const InfoData& d, const OwnedItem& it, u8 type, u8 up);

struct TipEntry {
    std::size_t row{};  ///< index into InfoData::info (= the read-state byte index)
    bool unread{};
};
/// 0xb9c480 / 0xb9c730: the visible tips in native order; `read` = bytes R+0x18 (may be shorter).
std::vector<TipEntry> VisibleTips(const InfoData& d, const Progress& p, std::span<const u8> read);

/// 0xc09d40: the next medal reward (nullptr when every reward was received).
const MedalRow* NextMedal(const InfoData& d, std::span<const std::string> received);

struct Objective {
    std::u32string main;
    std::vector<std::u32string> subs;
};
/// 0xc03c78 / 0xc02e90 for the current MAPGUIDE row id; `texts` = en/GOP_Text_Map.
std::optional<Objective> ObjectiveFor(const InfoData& d, const MapData& map, std::string_view guide,
                                      const Progress& p);

/// The native Defeated Monster List rows (0xb8c8b0): a library row is listed when the record holds its
/// unit (P+0x280) or its GOP_Monster row is not a boss (+0x98 Is_Boss); indices into InfoData::library.
std::vector<std::size_t> VisibleMonsters(const InfoData& d, const std::map<std::string, s32>& record);

/// Display text of a game string: "<b>"/"</>" dropped, "<--->" as an em dash, other tags kept out.
std::u32string CleanGameText(std::u32string_view s);

// ---------------------------------------------------------------------------------- live state
struct InfoRoots {
    bool ok{}; ///< every pin and the EGOPEnumProgressType enumerator table matched
};
/// Checks the code pins of the routes above and the enumerator table against the guest. Empty = ok.
std::string ResolveInfo(const GuestRead& read, std::uint64_t main_base, std::uint64_t main_size,
                        InfoRoots& roots);

struct MemberDetail {
    std::uint64_t field{};
    std::string personality; ///< PERSONALITY_* ("" = none)
    s32 level{}, exp{};
    StatInputs stats;
    struct Skill {
        std::string id; ///< GOP_Magic row
        u8 learn{}, timing{};
        bool operator==(const Skill&) const = default;
    };
    std::vector<Skill> skills;
    bool limited{}; ///< B+0x21 bLimitStockNum: the bag holds at most CarryLimit slots (0x8aa528)
    bool operator==(const MemberDetail&) const = default;
};
/// 0x8aa528: a bag with bLimitStockNum (B+0x21) is full at 20 slots (equipped ones included).
inline constexpr int CarryLimit = 20;
/// One member (C = roster entry with F = [C+0x58] == `field`): personality, EXP, stat inputs, the
/// owner bag and the skill list. Two passes must agree.
std::optional<MemberDetail> ReadMemberDetail(const GuestRead& read, const Roots& roots, std::uint64_t field);

/// The stat record the full-path getters read: F, or [F+0x1A8] while its controller F+0x1B0 holds a
/// shared reference (refs >= 1). nullopt when unreadable.
std::optional<std::uint64_t> StatRecord(const GuestRead& read, std::uint64_t field);
/// Strength as GetStr 0x89e2e0 returns it (both paths): clamp(floor((float)s+0x38) + s+0x70, 0, 999)
/// with s = StatRecord(field); no equipment term (helper 0x87ef78 returns 0). The battle detail's value.
std::optional<s32> ReadStrength(const GuestRead& read, std::uint64_t field);
/// One raw skill-list entry (F+0xA8, 0x24 bytes): +0x4 FName of the GOP_Magic row, +0xC learn, +0xD timing.
struct RawSkill {
    std::uint32_t name[2]{};
    u8 learn{}, timing{};
};
/// The skill list F+0xA8 / count F+0xB0 (0..256 entries; 0 = empty). nullopt when unreadable.
std::optional<std::vector<RawSkill>> ReadSkillEntries(const GuestRead& read, std::uint64_t field);

struct BagList {
    std::array<std::vector<OwnedItem>, 3> bags; ///< Item Bag (vocation 11), Equipment Bag (12), Important (13)
    bool operator==(const BagList&) const = default;
};
/// The bag objects (C+0x78) of the three shared bag owners (vocations 11..13, in that order); every
/// owner must be present exactly once.
std::optional<std::array<std::uint64_t, 3>> ReadBagOwners(const GuestRead& read, const Roots& roots);
/// The item list of a bag object B: B+0x28 TArray<TSharedPtr<Slot>>, Slot {count, equip, def}.
std::optional<std::vector<OwnedItem>> ReadBagItems(const GuestRead& read, const Roots& roots, std::uint64_t bag);
#ifdef DQ3_TEST_API // test-only API: defined for the dsmod-dq3 test target, not compiled into the module
/// All three bags (ReadBagOwners + ReadBagItems of each).
std::optional<BagList> ReadBags(const GuestRead& read, const Roots& roots);
#endif

struct JournalState {
    std::string guide;                   ///< current MAPGUIDE row
    std::vector<u8> tips_read;           ///< R+0x18 bytes
    std::vector<std::string> medals_got; ///< P+0x40
    s32 medals{};                        ///< P+0x34
    Progress progress;
    bool operator==(const JournalState& o) const {
        return guide == o.guide && tips_read == o.tips_read && medals_got == o.medals_got && medals == o.medals &&
               progress.bits == o.progress.bits;
    }
};
std::optional<JournalState> ReadJournalState(const GuestRead& read, const Roots& roots);

// ---------------------------------------------------------------------------------- art
/// True when `key` belongs to ComposeInfoArt.
bool IsInfoArtKey(std::string_view key);
/// fcard/<sprite|->/<sel>[/<w>] the 286 (or StripCardW(N)) x 188 field card: window + class sprite (+ gold outline)
/// portrait/<sprite|->        112 x 112 FieldMemory image frame with the member's sprite (2x, 104 rows)
/// itemicon/<cell>/<px>       item-type icon on the T_UI_Map_ItemBG_01 background (38 px for 32 px)
/// itemtype/<cell>/<px>       the item-type icon alone (dark grids)
/// ui/<name>/<w>x<h>          bag / nextguide / medal / book icons fitted (bagfit: the bag stretched)
/// box/<w>x<h>/<kind>         'slot' / 'slotsel' equipped-slot card (cream, thin / 3 px outline), 'sub' gold
///                            sub-tab box (dark fill + 2 px gold outline)
std::optional<Image> ComposeInfoArt(const RangeReader& read, std::string_view key, std::string* why = nullptr);

} // namespace dq3
