# SPDX-FileCopyrightText: Copyright 2026 Eden DSMod fork
# SPDX-License-Identifier: GPL-3.0-or-later

# Pokemon Brilliant Diamond 1.3.0 + Luminescent Platinum: Unity asset reader (lp_unity).
# Included from CMakeLists.txt, which defines the module target itself:
#   LP_UNITY_SOURCES              library sources: lp_unity, stb_truetype, bc_decoder and lz4.c
#                                 (do not add bc_decoder.cpp or lz4.c to the module again)
#   LP_UNITY_INCLUDE_DIRECTORIES  include directories those sources need (lz4, bc_decoder)
#   lp-unity-tool                 Linux dev CLI (EXCLUDE_FROM_ALL): decodes sprites with Eden's
#                                 CPU ASTC decoder, compares PNGs, dumps typetree objects, fonts
#   lp-unity-test                 synthetic unit test (BUILD_TESTING, Linux)
# The LZ4 block decoder is compiled in from the emulator's CPM cache, like Wonder's zstd.

enable_language(C)
file(GLOB LP_LZ4_LIB LIST_DIRECTORIES true "${EDEN_CPM_CACHE}/lz4/*/lib")
list(LENGTH LP_LZ4_LIB lp_lz4_count)
if(NOT lp_lz4_count EQUAL 1)
    message(FATAL_ERROR "Expected one lz4 source in ${EDEN_CPM_CACHE}/lz4; configure the compatible Eden Duo checkout first")
endif()
list(GET LP_LZ4_LIB 0 LP_LZ4_LIB)
set(LP_LZ4_SOURCES "${LP_LZ4_LIB}/lz4.c" "${LP_LZ4_LIB}/lz4.h")

set(LP_UNITY_SOURCES
    "${CMAKE_CURRENT_LIST_DIR}/lp_unity.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/lp_unity.h"
    "${CMAKE_CURRENT_LIST_DIR}/third_party/stb_truetype.h"
    "${EDEN_SOURCE_ROOT}/externals/bc_decoder/bc_decoder.cpp"
    ${LP_LZ4_SOURCES})
set(LP_UNITY_INCLUDE_DIRECTORIES "${LP_LZ4_LIB}" "${EDEN_SOURCE_ROOT}/externals/bc_decoder")

if(NOT ANDROID)
    # The tool decodes ASTC with Eden's own CPU decoder (video_core/textures/astc.cpp), the same
    # code the host's decode_astc runs. Its thread-pool header is replaced by a synchronous shim
    # generated here, and boost.container comes from the CPM cache (header-only).
    set(lp_shim_dir "${CMAKE_CURRENT_BINARY_DIR}/lp_astc_shim")
    file(WRITE "${lp_shim_dir}/video_core/textures/workers.h" [=[
// Generated by native/modules/lp.cmake: synchronous stand-in for Eden's texture thread pool.
#pragma once
#include <utility>
namespace Common {
class ThreadWorker {
public:
    template <typename F>
    void QueueWork(F&& work) {
        std::forward<F>(work)();
    }
    void WaitForRequests() {}
};
} // namespace Common
namespace Tegra::Texture {
inline Common::ThreadWorker& GetThreadWorkers() {
    static Common::ThreadWorker workers;
    return workers;
}
} // namespace Tegra::Texture
]=])
    file(GLOB lp_boost_includes LIST_DIRECTORIES true "${EDEN_CPM_CACHE}/boost/*/libs/*/include")
    set(LP_ASTC_SOURCE "${EDEN_SOURCE_ROOT}/src/video_core/textures/astc.cpp")

    add_executable(lp-unity-tool EXCLUDE_FROM_ALL
        "${CMAKE_CURRENT_LIST_DIR}/lp_unity_tool.cpp" "${CMAKE_CURRENT_LIST_DIR}/lp_poketch.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/lp_assets.cpp"
        ${LP_UNITY_SOURCES} "${LP_ASTC_SOURCE}")
    target_compile_features(lp-unity-tool PRIVATE cxx_std_20)
    target_include_directories(lp-unity-tool BEFORE PRIVATE "${lp_shim_dir}")
    target_include_directories(lp-unity-tool PRIVATE "${CMAKE_CURRENT_LIST_DIR}"
        "${EDEN_SOURCE_ROOT}/src" "${EDEN_SOURCE_ROOT}/externals/stb"
        ${LP_UNITY_INCLUDE_DIRECTORIES} ${lp_boost_includes})
    set_source_files_properties("${LP_ASTC_SOURCE}" PROPERTIES COMPILE_OPTIONS "-w")

    if(BUILD_TESTING AND COMMAND dsmod_add_test)
        dsmod_add_test(lp-unity KEEP_ASSERTS
            SOURCES "${CMAKE_CURRENT_LIST_DIR}/lp_unity_test.cpp" ${LP_UNITY_SOURCES}
            INCLUDE_DIRECTORIES ${LP_UNITY_INCLUDE_DIRECTORIES})
    endif()
endif()
