// SPDX-FileCopyrightText: Copyright 2026 Eden DSMod fork
// SPDX-License-Identifier: GPL-3.0-or-later

// p5r_recipes.h against a Pillow reference replay of the same recipes.
//   p5r-recipes-test <table.rec> <testdata dir> <FONT0.FNT | --romfs=<root>> [max allowed diff]
// --romfs=<root>: the real decoders (p5r_assets::Romfs over <root>/CPK/ALL_USEU.CPK +
// PATCH1.CPK) feed the engine instead of the PNG extractions -- the module's exact path.
// testdata (generated by the reference tool): ref/<id>.png = Pillow output of every recipe;
// src/s/<alias>/<id>.png and src/d/<romfs path>.png = the decoded inputs (test-only loader standing
// in for p5r_assets). Without arguments only the built-in op checks run (no local files needed).
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <map>
#include <sstream>

#define STB_IMAGE_IMPLEMENTATION
#define STBI_ONLY_PNG
#include "stb_image.h"

#include "p5r_recipes.h"
#include "p5r_romfs_local.h"

namespace {
using p5r_recipes::Image;

bool LoadPng(const std::string& path, Image& out) {
    int w = 0, h = 0, n = 0;
    unsigned char* px = stbi_load(path.c_str(), &w, &h, &n, 4);
    if (!px)
        return false;
    out.w = uint32_t(w);
    out.h = uint32_t(h);
    out.rgba.assign(px, px + size_t(w) * h * 4);
    stbi_image_free(px);
    return true;
}

std::string ReadFile(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    std::stringstream ss;
    ss << f.rdbuf();
    return ss.str();
}

// Test-only stand-in for p5r_assets (local PNG extractions of the same romfs files).
class LocalSources : public p5r_recipes::Sources {
public:
    LocalSources(std::string dir, std::string fnt) : dir_(std::move(dir)), fnt_(std::move(fnt)) {}
    std::map<std::string, std::string> alias_of_path; // romfs path -> alias (src/s/<alias>/)
    bool Sprite(std::string_view spd, uint32_t id, Image& out) override {
        const auto it = alias_of_path.find(std::string(spd));
        return it != alias_of_path.end() &&
               LoadPng(dir_ + "/src/s/" + it->second + "/" + std::to_string(id) + ".png", out);
    }
    bool Dds(std::string_view path, Image& out) override {
        const std::string key(path);
        if (const auto it = cache_.find(key); it != cache_.end()) {
            out = it->second;
            return true;
        }
        if (!LoadPng(dir_ + "/src/d/" + key + ".png", out))
            return false;
        cache_[key] = out;
        return true;
    }
    bool FontFile(std::vector<uint8_t>& fnt) override {
        const std::string s = ReadFile(fnt_);
        fnt.assign(s.begin(), s.end());
        return !fnt.empty();
    }

private:
    std::string dir_, fnt_;
    std::map<std::string, Image> cache_;
};

// (max channel diff, differing pixels); rgb ignored where both alphas are 0 (like the package
// comparison tool)
std::pair<int, size_t> Diff(const Image& a, const Image& b) {
    if (a.w != b.w || a.h != b.h)
        return {9999, 0};
    int m = 0;
    size_t n = 0;
    for (size_t i = 0; i < a.rgba.size(); i += 4) {
        const bool vis = a.rgba[i + 3] || b.rgba[i + 3];
        int pm = std::abs(int(a.rgba[i + 3]) - int(b.rgba[i + 3]));
        if (vis)
            for (int c = 0; c < 3; ++c)
                pm = std::max(pm, std::abs(int(a.rgba[i + c]) - int(b.rgba[i + c])));
        m = std::max(m, pm);
        n += pm != 0;
    }
    return {m, n};
}

int failures = 0;
void Expect(bool ok, const char* what) {
    if (!ok) {
        std::printf("FAIL %s\n", what);
        ++failures;
    }
}

// Hand-checked values of the Pillow maths (no local files needed).
void BuiltinChecks() {
    namespace pil = p5r_recipes::pil;
    Expect(pil::PyRound(2.5) == 2 && pil::PyRound(3.5) == 4 && pil::PyRound(-0.5) == 0,
           "round half even");
    Expect(pil::FloorDiv(-3, 2) == -2 && pil::FloorDiv(3, 2) == 1, "floor division");
    Expect(pil::Round15(0.9961946980917455) == 0.996194698091746, "round(x, 15)");
    uint8_t d[4] = {0, 0, 0, 0};
    const uint8_t s[4] = {255, 255, 255, 77};
    pil::CompositePixel(d, s);
    Expect(d[0] == 255 && d[3] == 77, "composite onto transparent keeps the source");
    Image im;
    p5r_recipes::Alloc(im, 8, 8);
    p5r_recipes::pil::Canvas cv{im, nullptr, {255, 255, 255, 255}};
    p5r_recipes::pil::PolygonFill(cv, {0, 0, 7, 0, 7, 7, 0, 7});
    size_t on = 0;
    for (size_t i = 3; i < im.rgba.size(); i += 4)
        on += im.rgba[i] == 255;
    Expect(on == 64, "polygon covers its closed box");
}
} // namespace

int main(int argc, char** argv) {
    BuiltinChecks();
    if (argc < 4) {
        std::printf("%s (built-in checks only)\n", failures ? "FAILED" : "OK");
        return failures ? 1 : 0;
    }
    const int allowed = argc > 4 ? std::atoi(argv[4]) : 0;
    const std::string table = ReadFile(argv[1]), dir = argv[2];
    p5r_recipes::Book book;
    if (!book.Parse(table)) {
        std::printf("FAIL cannot parse %s\n", argv[1]);
        return 1;
    }
    const std::string mode = argv[3];
    LocalSources local(dir, mode);
    p5r_assets::Romfs romfs;
    std::unique_ptr<p5r_recipes::RomfsSources> rs;
    if (mode.rfind("--romfs=", 0) == 0) {
        const auto t0 = std::chrono::steady_clock::now();
        if (!romfs.Open(p5r_assets::LocalDirReader(mode.substr(8)))) {
            std::printf("FAIL romfs: %s\n", romfs.Error().c_str());
            return 1;
        }
        std::printf("romfs open %.0f ms: %s\n",
                    std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - t0)
                        .count(),
                    romfs.Describe().c_str());
        rs = std::make_unique<p5r_recipes::RomfsSources>(romfs);
    }
    p5r_recipes::Sources& src = rs ? static_cast<p5r_recipes::Sources&>(*rs) : local;
    {
        std::istringstream lines(table);
        std::string l;
        while (std::getline(lines, l))
            if (!l.empty() && l[0] == '@') {
                const size_t sp = l.find(' ');
                local.alias_of_path[l.substr(sp + 1)] = l.substr(1, sp - 1);
            }
    }
    p5r_recipes::Engine eng(book, src);
    std::map<int, int> hist;
    struct Row {
        int diff;
        size_t px;
        std::string id;
        double ms;
    };
    std::vector<Row> rows;
    double total_ms = 0;
    size_t built = 0, broken = 0;
    std::vector<std::string> ids;
    book.ForEach([&](const std::string& id, std::string_view) { ids.push_back(id); });
    std::sort(ids.begin(), ids.end());
    for (const auto& id : ids) {
        Image got, want;
        std::string err;
        const auto t0 = std::chrono::steady_clock::now();
        const bool ok = eng.Build(id, got, &err);
        const double ms =
            std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - t0)
                .count();
        total_ms += ms;
        if (!ok) {
            std::printf("FAIL build %s: %s\n", id.c_str(), err.c_str());
            ++broken;
            continue;
        }
        if (!LoadPng(dir + "/ref/" + id + ".png", want)) {
            std::printf("FAIL no reference for %s\n", id.c_str());
            ++broken;
            continue;
        }
        ++built;
        const auto [d, n] = Diff(got, want);
        hist[d == 9999 ? 9999
             : d == 0  ? 0
             : d <= 1  ? 1
             : d <= 2  ? 2
             : d <= 4  ? 4
             : d <= 16 ? 16
                       : 255]++;
        rows.push_back({d, n, id, ms});
    }
    std::sort(rows.begin(), rows.end(), [](const Row& a, const Row& b) { return a.diff > b.diff; });
    std::printf("%zu recipes built, %zu failed, %.0f ms total\n", built, broken, total_ms);
    std::printf("max channel diff histogram:");
    for (const auto& [k, v] : hist)
        std::printf(" <=%d:%d", k, v);
    std::printf("\nworst:\n");
    for (size_t i = 0; i < std::min<size_t>(rows.size(), 25); ++i)
        std::printf("  %s diff %d px %zu (%.1f ms)\n", rows[i].id.c_str(), rows[i].diff, rows[i].px,
                    rows[i].ms);
    std::sort(rows.begin(), rows.end(), [](const Row& a, const Row& b) { return a.ms > b.ms; });
    std::printf("slowest:\n");
    for (size_t i = 0; i < std::min<size_t>(rows.size(), 8); ++i)
        std::printf("  %s %.1f ms\n", rows[i].id.c_str(), rows[i].ms);
    const bool pass = failures == 0 && broken == 0 &&
                      (rows.empty() || std::all_of(rows.begin(), rows.end(), [&](const Row& r) {
                           return r.diff <= allowed;
                       }));
    std::printf("%s\n", pass ? "OK" : "FAILED");
    return pass ? 0 : 1;
}
